version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/server.dockerfile
      args:
        PHP_VERSION_ARG: ${PHP_VERSION:-8.4}
    image: basic-app/php
    container_name: app
    working_dir: /var/www
    tty: true
    environment:
      LC_ALL: ${LC_ALL}
      TZ: ${TZ}
    volumes:
      - ../project:/var/www
      - ./php/00-php.ini:/etc/php/${PHP_VERSION:-8.4}/cli/conf.d/00-php.ini
    networks:
      - default

  fpm:
    build:
      context: .
      dockerfile: ./dockerfiles/fpm.dockerfile
      args:
        PHP_VERSION_ARG: ${PHP_VERSION:-8.4}
    image: basic-fpm/php
    container_name: fpm
    working_dir: /var/www
    tty: true
    environment:
      LC_ALL: ${LC_ALL}
      TZ: ${TZ}
    volumes:
      - ../project:/var/www
      - ./fpm/fpm.conf:/etc/php/${PHP_VERSION:-8.4}/fpm/pool.d/www.conf
      - ./fpm/00-php.ini:/usr/local/etc/php/conf.d/00-php.ini
    networks:
      - default

  webserver:
    image: nginx:alpine
    container_name: webserver
    ports:
      - ${SERVER_HTTP_PORT:-80}:80
      - ${SERVER_HTTPS_PORT:-443}:443
    tty: true
    volumes:
      - ../project:/var/www
      - ./webserver:/etc/nginx/conf.d
      - ./webserver/ssl:/var/www/certs
    networks:
      - default

  mysql:
    image: mariadb:10.5.9
    command: [ "--max-allowed-packet=512M" ]
    container_name: mysql
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-my_project}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql/storage:/var/lib/mysql:delegated
      - ./mysql/conf:/etc/mysql/conf.d
    networks:
      - default

  phpmyadmin:
    image: bitnami/phpmyadmin:5.2.0-debian-11-r43
    tty: true
    ports:
      - ${PHPMYADMIN_HTTP_PORT:-8081}:8443
    environment:
      DATABASE_HOST: mysql
    networks:
      - default

  node:
    image: node:${NODE_VERSION:-20.16.0}-alpine${NODE_ALPINE_VERSION:-3.20}
    container_name: node
    tty: true
    working_dir: /var/www
    volumes:
      - ../project:/var/www
      - ./webserver/ssl:/var/www/certs
    ports:
      - ${NODE_WEBSOCKET_PORT:-3000}:3000
    command: npm run start
    networks:
      - default

networks:
  default:
    driver: bridge